/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../src/components/ErrorMessage/403.vue')['default']
    404: typeof import('./../src/components/ErrorMessage/404.vue')['default']
    500: typeof import('./../src/components/ErrorMessage/500.vue')['default']
    ColSetting: typeof import('./../src/components/ProTable/components/ColSetting.vue')['default']
    ComparisonCom: typeof import('./../src/components/ComparisonCom/index.vue')['default']
    ECharts: typeof import('./../src/components/ECharts/index.vue')['default']
    Grid: typeof import('./../src/components/Grid/index.vue')['default']
    GridItem: typeof import('./../src/components/Grid/components/GridItem.vue')['default']
    Img: typeof import('./../src/components/Upload/Img.vue')['default']
    Imgs: typeof import('./../src/components/Upload/Imgs.vue')['default']
    ImportExcel: typeof import('./../src/components/ImportExcel/index.vue')['default']
    Loading: typeof import('./../src/components/Loading/index.vue')['default']
    Pagination: typeof import('./../src/components/ProTable/components/Pagination.vue')['default']
    ProTable: typeof import('./../src/components/ProTable/index.vue')['default']
    QueryCard: typeof import('./../src/components/QueryCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../src/components/SearchForm/index.vue')['default']
    SearchFormItem: typeof import('./../src/components/SearchForm/components/SearchFormItem.vue')['default']
    SelectFilter: typeof import('./../src/components/SelectFilter/index.vue')['default']
    SelectIcon: typeof import('./../src/components/SelectIcon/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    SwitchDark: typeof import('./../src/components/SwitchDark/index.vue')['default']
    TableColumn: typeof import('./../src/components/ProTable/components/TableColumn.vue')['default']
    TreeFilter: typeof import('./../src/components/TreeFilter/index.vue')['default']
  }
}
